process.env.TURSO_DATABASE_URL = "http://127.0.0.1:8081";
delete process.env.TURSO_AUTH_TOKEN;
process.env.SESSION_SECRET = "test-session-secret-0123456789abcdefghij";
process.env.ADMIN_TOKEN = "test-admin-token";
process.env.RESEND_API_KEY = "test-resend-key";
process.env.CONTACT_MAIL_TO = "owner@example.com";
process.env.CONTACT_MAIL_FROM = "Mado-Web Contact <onboarding@resend.dev>";
process.env.CLOUDINARY_CLOUD_NAME = "test-cloud";
process.env.CLOUDINARY_API_KEY = "test-api-key";
process.env.CLOUDINARY_API_SECRET = "test-api-secret";
